name: CI

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r  flask/requirements.txt
        working-directory: ./flask 
      - name: Lint code
        run: |
          pip install flake8
          flake8 .

      - name: Format code
        run: |
          pip install black
          black .

      - name: Run tests
        run: |
          pip install pytest
          pytest
